# Generated by Django 4.1.7 on 2023-04-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='challenge_amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='battle',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
    ]
