# Generated by Django 4.1.7 on 2023-04-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_alter_battle_challenge_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='link',
        ),
    ]
