# Generated by Django 4.1.7 on 2023-04-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_remove_battle_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='cash_pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battle',
            name='number_of_users',
            field=models.IntegerField(default=0),
        ),
    ]
