# Generated by Django 4.1.7 on 2023-04-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0004_battle_cash_pool_battle_number_of_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_id', models.IntegerField(default=1)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
